/**
 * @packageDocumentation
 * @module api.functional.mail.senders.emails
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { AuthorizationHeaders } from "../../../../core.types";
import type { GetEmailsRequest } from "../../../../mail.controller.types";

/**
 * Get List of emails from a {@link senderId }
 * 
 * @param senderId Sender ID
 * @returns List of Emails
 * 
 * @controller MailController.getEmails
 * @path GET /mail/senders/:senderId/emails
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getEmails(
    connection: IConnection<getEmails.Headers>,
    senderId: number,
): Promise<getEmails.Output> {
    return PlainFetcher.fetch(
        connection,
        {
            ...getEmails.METADATA,
            path: getEmails.path(senderId),
        } as const,
    );
}
export namespace getEmails {
    export type Headers = Resolved<AuthorizationHeaders>;
    export type Output = Primitive<GetEmailsRequest.Response>;

    export const METADATA = {
        method: "GET",
        path: "/mail/senders/:senderId/emails",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (senderId: number): string => {
        return `/mail/senders/${encodeURIComponent(senderId ?? "null")}/emails`;
    }
}