/**
 * @packageDocumentation
 * @module api.functional.mail.senders
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { AuthorizationHeaders } from "../../../core.types";
import type { GetSenders } from "../../../mail.controller.types";

export * as emails from "./emails";
export * as $delete from "./$delete";
export * as block from "./block";
export * as unblock from "./unblock";

/**
 * Get List of Senders Asynchoronously
 * 
 * @returns List of Senders
 * 
 * @controller MailController.getSenders
 * @path GET /mail/senders
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getSenders(
    connection: IConnection<getSenders.Headers>,
): Promise<getSenders.Output> {
    return PlainFetcher.fetch(
        connection,
        {
            ...getSenders.METADATA,
            path: getSenders.path(),
        } as const,
    );
}
export namespace getSenders {
    export type Headers = Resolved<AuthorizationHeaders>;
    export type Output = Primitive<GetSenders.Response>;

    export const METADATA = {
        method: "GET",
        path: "/mail/senders",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (): string => {
        return `/mail/senders`;
    }
}