/**
 * @packageDocumentation
 * @module api.functional.mail.senders
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

export * as emails from "./emails";
export * as $delete from "./$delete";
export * as block from "./block";

/**
 * @controller MailController.getSenders
 * @path GET /mail/senders
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getSenders(
    connection: IConnection,
): Promise<void> {
    return PlainFetcher.fetch(
        connection,
        {
            ...getSenders.METADATA,
            path: getSenders.path(),
        } as const,
    );
}
export namespace getSenders {

    export const METADATA = {
        method: "GET",
        path: "/mail/senders",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (): string => {
        return `/mail/senders`;
    }
}