/**
 * @packageDocumentation
 * @module api.functional.mail.senders
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { AuthorizationHeaders } from "../../../core.types";
import type { GetSenders } from "../../../mail.controller.types";

export * as emails from "./emails";
export * as $delete from "./$delete";
export * as delete_many from "./delete_many";
export * as block from "./block";
export * as unblock from "./unblock";

/**
 * Get List of Senders. Maximum 100 at a time
 * 
 * @returns List of Senders
 * 
 * @controller MailController.getSenders
 * @path GET /mail/senders
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getSenders(
    connection: IConnection<getSenders.Headers>,
    requestQuery: getSenders.Query,
): Promise<getSenders.Output> {
    return PlainFetcher.fetch(
        connection,
        {
            ...getSenders.METADATA,
            path: getSenders.path(requestQuery),
        } as const,
    );
}
export namespace getSenders {
    export type Headers = Resolved<AuthorizationHeaders>;
    export type Query = Resolved<GetSenders.QueryParams>;
    export type Output = Primitive<GetSenders.Response>;

    export const METADATA = {
        method: "GET",
        path: "/mail/senders",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (requestQuery: getSenders.Query): string => {
        const variables: Record<any, any> = requestQuery as any;
        const search: URLSearchParams = new URLSearchParams();
        for (const [key, value] of Object.entries(variables))
            if (value === undefined) continue;
            else if (Array.isArray(value))
                value.forEach((elem) => search.append(key, String(elem)));
            else
                search.set(key, String(value));
        const encoded: string = search.toString();
        return `/mail/senders${encoded.length ? `?${encoded}` : ""}`;;
    }
}