/**
 * @packageDocumentation
 * @module api.functional.mail.senders.$delete
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

/**
 * @controller MailController.deleteSender
 * @path DELETE /mail/senders/:senderId/delete
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deleteSender(
    connection: IConnection,
    senderId: string,
): Promise<void> {
    return PlainFetcher.fetch(
        connection,
        {
            ...deleteSender.METADATA,
            path: deleteSender.path(senderId),
        } as const,
    );
}
export namespace deleteSender {

    export const METADATA = {
        method: "DELETE",
        path: "/mail/senders/:senderId/delete",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (senderId: string): string => {
        return `/mail/senders/${encodeURIComponent(senderId ?? "null")}/delete`;
    }
}