/**
 * @packageDocumentation
 * @module api.functional.mail.senders.$delete
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import type { IConnection, Resolved } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { AuthorizationHeaders } from "../../../../core.types";

/**
 * Delete all emails from a sender
 * 
 * @controller MailController.deleteSender
 * @path DELETE /mail/senders/:senderId/delete
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deleteSender(
    connection: IConnection<deleteSender.Headers>,
    senderId: number,
): Promise<void> {
    return PlainFetcher.fetch(
        connection,
        {
            ...deleteSender.METADATA,
            path: deleteSender.path(senderId),
        } as const,
    );
}
export namespace deleteSender {
    export type Headers = Resolved<AuthorizationHeaders>;

    export const METADATA = {
        method: "DELETE",
        path: "/mail/senders/:senderId/delete",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (senderId: number): string => {
        return `/mail/senders/${encodeURIComponent(senderId ?? "null")}/delete`;
    }
}