/**
 * @packageDocumentation
 * @module api.functional.user
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

/**
 * @controller UserController.getCurrentUser
 * @path GET /user
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getCurrentUser(
    connection: IConnection,
): Promise<void> {
    return PlainFetcher.fetch(
        connection,
        {
            ...getCurrentUser.METADATA,
            path: getCurrentUser.path(),
        } as const,
    );
}
export namespace getCurrentUser {

    export const METADATA = {
        method: "GET",
        path: "/user",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (): string => {
        return `/user`;
    }
}