/**
 * @packageDocumentation
 * @module api.functional.mail.senders.block
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

/**
 * @controller MailController.blockSender
 * @path DELETE /mail/senders/:senderId/block
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function blockSender(
    connection: IConnection,
    senderId: string,
): Promise<void> {
    return PlainFetcher.fetch(
        connection,
        {
            ...blockSender.METADATA,
            path: blockSender.path(senderId),
        } as const,
    );
}
export namespace blockSender {

    export const METADATA = {
        method: "DELETE",
        path: "/mail/senders/:senderId/block",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (senderId: string): string => {
        return `/mail/senders/${encodeURIComponent(senderId ?? "null")}/block`;
    }
}